Database Refactor
OpenFusionProject/OpenFusion pull request #181
Opened 2020-12-07 20:03 UTC by kamilprzyb

2020-12-12 06:38 UTC, Raymonf requested changes
seeing sqlite_orm.h gone makes me happy :)

2020-12-12 06:38 UTC, Raymonf commented on src/CNLoginServer.cpp
> +
bruh

2020-12-12 06:38 UTC, Raymonf commented on src/CNLoginServer.cpp
> +    std::cout << "[WARN] Login Server: Database failed to finish character creation!" << std::endl;
bruh

2020-12-12 06:38 UTC, Raymonf commented on src/settings.cpp
> +    MONITORINTERVAL = reader.GetInteger("monitor", "interval", MONITORINTERVAL);
bruh

2020-12-14 02:56 UTC, CakeLancelot commented
Merged manually.

2020-12-14 02:56 UTC, closed without merging